"""message full json

Revision ID: 2d7daa8b8a91
Revises: a5e4b84f57bd
Create Date: 2024-07-08 21:45:54.114096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7daa8b8a91'
down_revision: Union[str, None] = 'a5e4b84f57bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_json_data', sa.String(), nullable=False, default="",
                                       server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message_json_data')
    # ### end Alembic commands ###
