"""custom_emoji

Revision ID: 7b2ff0f9c2d2
Revises: caf77c1e165e
Create Date: 2024-05-11 11:43:37.206164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2ff0f9c2d2'
down_revision: Union[str, None] = 'caf77c1e165e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reaction', sa.Column('custom_document_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('reaction', 'custom_document_id')
    # ### end Alembic commands ###
